apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: courier-fare-calculator-hpa
  namespace: courier-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: courier-fare-calculator
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80