apiVersion: v1
kind: Service
metadata:
  name: commission-service-service
  namespace: courier-services
  labels:
    app: commission-service
    domain: courier-services
spec:
  selector:
    app: commission-service
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
