spring:
  application:
    name: customer-onboarding-service
  datasource:
    url: jdbc:postgresql://localhost:5432/courier_services?useSSL=false&serverTimezone=UTC
    username: courier_user
    password: courier_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 8090
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Customer onboarding service specific configuration
customer-onboarding:
  verification:
    kyc-enabled: true
    document-upload-enabled: true
    max-file-size: 10MB
  notifications:
    email-enabled: true
    sms-enabled: true
  registration:
    auto-approval: false
    require-verification: true