apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: corporate-admin-hpa
  namespace: courier-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: corporate-admin
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
