apiVersion: v1
kind: Service
metadata:
  name: corporate-admin-service
  namespace: courier-services
  labels:
    app: corporate-admin
    domain: courier-services
spec:
  selector:
    app: corporate-admin
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
