apiVersion: v1
kind: Service
metadata:
  name: infrastructure-service
  namespace: courier-services
  labels:
    app: infrastructure
    domain: courier-services
spec:
  selector:
    app: infrastructure
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
