server:
  port: 8080
  servlet:
    context-path: /global-hq-admin

spring:
  application:
    name: global-hq-admin
  
  datasource:
    url: jdbc:postgresql://localhost:5432/global_hq_admin_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true
    clean-disabled: true
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.socialecommerceecosystem.com
          jwk-set-uri: https://auth.socialecommerceecosystem.com/.well-known/jwks.json

  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    discovery:
      enabled: true
      service-id: config-server
  
  # Distributed Tracing Configuration
  sleuth:
    sampler:
      probability: 1.0
    baggage:
      remote-fields: x-tenant-id
      correlation-fields: x-tenant-id
    opentracing:
      enabled: true
    web:
      client:
        enabled: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    service:
      name: ${spring.application.name}
    message-timeout: 5

# Eureka client configuration  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

# API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    
# Logging configuration
logging:
  level:
    root: INFO
    com.socialecommerceecosystem: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/global-hq-admin.log

# Application-specific configuration
global-hq-admin:
  security:
    allowed-origins: http://localhost:3000,https://admin.socialecommerceecosystem.com
    api-key-header-name: X-API-KEY
    jwt:
      token-validity-seconds: 86400
  metrics:
    scheduler:
      enabled: true
      cron: "0 0 * * * *"  # Hourly
  integration:
    regional-systems:
      health-check-enabled: true
      health-check-interval-seconds: 300
    notification:
      email-enabled: true
      sms-enabled: false
  multi-region:
    enabled: true
    default-region-code: GLOBAL
    cache-timeout-seconds: 300
    health-check-interval-seconds: 60
    max-retry-attempts: 3
    sync-strategy: BIDIRECTIONAL
    regions:
      - code: GLOBAL
        name: Global Headquarters
        api-endpoint: https://api.socialecommerceecosystem.com/global-hq-admin
        active: true
        sync-interval-seconds: 900
      - code: NAM
        name: North America
        api-endpoint: https://api.nam.socialecommerceecosystem.com/regional-admin
        active: true
        sync-interval-seconds: 900
      - code: EUR
        name: Europe
        api-endpoint: https://api.eur.socialecommerceecosystem.com/regional-admin
        active: true
        sync-interval-seconds: 900
      - code: APAC
        name: Asia Pacific
        api-endpoint: https://api.apac.socialecommerceecosystem.com/regional-admin
        active: true
        sync-interval-seconds: 900
      - code: AFR
        name: Africa
        api-endpoint: https://api.afr.socialecommerceecosystem.com/regional-admin
        active: true
        sync-interval-seconds: 900
      - code: LAT
        name: Latin America
        api-endpoint: https://api.lat.socialecommerceecosystem.com/regional-admin
        active: true
        sync-interval-seconds: 900
