server:
  port: 8081
  servlet:
    context-path: /regional-admin

spring:
  application:
    name: regional-admin-system
  
  datasource:
    url: jdbc:postgresql://localhost:5432/regional_admin_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.socialecommerceecosystem.com
          jwk-set-uri: https://auth.socialecommerceecosystem.com/.well-known/jwks.json
          
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    discovery:
      enabled: true
      service-id: config-server

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

# API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# Logging configuration
logging:
  level:
    root: INFO
    com.socialecommerceecosystem: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/regional-admin.log

# Application-specific configuration
regional-admin:
  security:
    allowed-origins: http://localhost:3000,https://regional.socialecommerceecosystem.com
    api-key-header-name: X-API-KEY
    jwt:
      token-validity-seconds: 86400
  metrics:
    scheduler:
      enabled: true
      cron: "0 */15 * * * *"  # Every 15 minutes
  integration:
    global-hq:
      url: http://localhost:8080/global-hq-admin
      sync-interval-minutes: 30
    local-courier-locations:
      health-check-enabled: true
      health-check-interval-seconds: 180
    notification:
      email-enabled: true
      sms-enabled: true
  location:
    auto-deactivation-days: 30  # Deactivate locations with no activity for 30 days
    capacity-warning-threshold: 85  # Warning when capacity reaches 85%
  geocoding:
    provider: google
    api-key: ${GEOCODING_API_KEY:your-api-key-placeholder}
