apiVersion: v1
kind: Service
metadata:
  name: customer-onboarding-service
  namespace: courier-services
  labels:
    app: customer-onboarding-service
    domain: courier-services
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8310
    targetPort: 8310
    protocol: TCP
    name: http
  selector:
    app: customer-onboarding-service
---
apiVersion: v1
kind: Service
metadata:
  name: customer-onboarding-service-nodeport
  namespace: courier-services
  labels:
    app: customer-onboarding-service
    domain: courier-services
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8310
    targetPort: 8310
    protocol: TCP
    name: http
    nodePort: 30310
  selector:
    app: customer-onboarding-service