apiVersion: v1
kind: Secret
metadata:
  name: courier-locations-db-credentials
  namespace: micro-social-ecommerce
type: Opaque
stringData:
  username: postgres
  password: ${DB_PASSWORD}  # Will be replaced by CI/CD pipeline
  url: jdbc:postgresql://courier-locations-db:5432/courier_locations
