apiVersion: v1
kind: Service
metadata:
  name: readiness-reports-service
  namespace: courier-services
  labels:
    app: readiness-reports
    domain: courier-services
spec:
  selector:
    app: readiness-reports
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
