apiVersion: v1
kind: Service
metadata:
  name: user-mobile-app-service
  namespace: courier-services
  labels:
    app: user-mobile-app
    domain: courier-services
spec:
  selector:
    app: user-mobile-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
