apiVersion: v1
kind: ConfigMap
metadata:
  name: courier-onboarding-config
  labels:
    app: courier-onboarding
data:
  database-url: "jdbc:postgresql://postgres:5432/courier_onboarding"
  document-storage-location: "/data/documents"
  app.services.notification-service: "http://notification-service/api/v1/notifications"
  app.services.delivery-service: "http://delivery-service/api/v1/deliveries"
  app.auth.service-url: "http://auth-service/api/v1/auth"
