apiVersion: v1
kind: Service
metadata:
  name: courier-onboarding-service
  namespace: courier-services
  labels:
    app: courier-onboarding
    domain: courier-services
spec:
  selector:
    app: courier-onboarding
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
