apiVersion: v1
kind: Service
metadata:
  name: branch-courier-app-service
  namespace: courier-services
  labels:
    app: branch-courier-app
    domain: courier-services
spec:
  selector:
    app: branch-courier-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP