apiVersion: v1
kind: Service
metadata:
  name: international-shipping-service
  namespace: courier-services
  labels:
    app: international-shipping
    domain: courier-services
spec:
  selector:
    app: international-shipping
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
