apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-events-service
  namespace: courier-services
  labels:
    app: courier-events-service
    domain: courier-services
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: courier-events-service
  template:
    metadata:
      labels:
        app: courier-events-service
        domain: courier-services
        tier: backend
    spec:
      containers:
      - name: courier-events-service
        image: ${DOCKER_REGISTRY}/courier-events-service:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: courier-events-service-secret
              key: database-url
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: courier-events-service-config
              key: kafka-brokers
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: courier-events-service-secret
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: courier-events-service-config
  namespace: courier-services
data:
  kafka-brokers: "kafka:9092"
  log-level: "info"
---
apiVersion: v1
kind: Secret
metadata:
  name: courier-events-service-secret
  namespace: courier-services
type: Opaque
data:
  database-url: ${DATABASE_URL_BASE64}
  redis-url: ${REDIS_URL_BASE64}