apiVersion: v1
kind: Service
metadata:
  name: courier-events-service
  namespace: courier-services
  labels:
    app: courier-events-service
    domain: courier-services
spec:
  selector:
    app: courier-events-service
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP