apiVersion: v1
kind: Service
metadata:
  name: courier-network-locations-service
  namespace: courier-services
  labels:
    app: courier-network-locations
    domain: courier-services
spec:
  selector:
    app: courier-network-locations
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
