version: '3.8'

services:
  courier-pickup-engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: courier-pickup-engine_container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    networks:
      - exalt-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

networks:
  exalt-network:
    external: true
