spring:
  application:
    name: commission-service
  datasource:
    url: jdbc:mysql://localhost:3306/courier_services?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8085
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Commission service specific configuration
commission:
  calculation:
    max-batch-size: 100
    default-period-days: 7
  payment:
    schedule: 0 0 2 * * ?  # 2 AM every day
    method: AUTO_TRANSFER
    timeout-seconds: 30
    retry:
      max-attempts: 3
      backoff-seconds: 60
  integration:
    payout-service:
      url: http://payout-service:8084
      timeout-ms: 5000
