apiVersion: apps/v1
kind: Deployment
metadata:
  name: courier-pickup-engine
  namespace: courier-services
  labels:
    app: courier-pickup-engine
    domain: courier-services
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: courier-pickup-engine
  template:
    metadata:
      labels:
        app: courier-pickup-engine
        domain: courier-services
        tier: backend
    spec:
      containers:
      - name: courier-pickup-engine
        image: ${DOCKER_REGISTRY}/courier-pickup-engine:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: courier-pickup-engine-secret
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: courier-pickup-engine-secret
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Secret
metadata:
  name: courier-pickup-engine-secret
  namespace: courier-services
type: Opaque
data:
  database-url: ${DATABASE_URL_BASE64}
  redis-url: ${REDIS_URL_BASE64}