apiVersion: v1
kind: Service
metadata:
  name: courier-pickup-engine
  namespace: courier-services
  labels:
    app: courier-pickup-engine
    domain: courier-services
spec:
  selector:
    app: courier-pickup-engine
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP