spring:
  application:
    name: courier-management-service
  datasource:
    url: jdbc:postgresql://localhost:5432/courier_management
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    baseUrl: http://zipkin:9411
    enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  # 100% of traces (reduce in production)
    web:
      client:
        enabled: true
    async:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    config:
      enabled: false

server:
  port: 8081
  servlet:
    context-path: /api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.web: INFO
    com.microecosystem.courier.management: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.cloud.sleuth: DEBUG

# Swagger API documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# For production, the below properties should be externalized in a secured manner
# via the config server or environment variables
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

# Integration with Routing Service
routing-service:
  base-url: http://routing-service:8084

# Integration with Tracking Service
tracking-service:
  base-url: http://tracking-service:8083

# Firebase Cloud Messaging config for mobile app notifications
fcm:
  service-account-file: firebase-service-account.json

# Assignment algorithm configuration
assignment:
  algorithm:
    # Factors and their weights for courier suitability score calculation
    proximity-weight: 0.4
    workload-weight: 0.3
    rating-weight: 0.1
    success-rate-weight: 0.1
    on-time-rate-weight: 0.1
    # Max radius in kilometers to search for couriers
    max-search-radius-km: 10.0
    # Batch optimization settings
    batch-size: 50
    optimization-interval-seconds: 60 