apiVersion: v1
kind: Service
metadata:
  name: courier-management-service
  namespace: courier-services
  labels:
    app: courier-management
    domain: courier-services
spec:
  selector:
    app: courier-management
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
