#!/bin/bash
# Script to install Java 17 and Maven in WSL

echo "==============================================="
echo "Installing Java 17 and Maven in WSL"
echo "==============================================="
echo ""
echo "Please run these commands in your WSL terminal:"
echo ""
echo "# Update package list"
echo "sudo apt update"
echo ""
echo "# Install Java 17 JDK"
echo "sudo apt install openjdk-17-jdk -y"
echo ""
echo "# Install Maven"
echo "sudo apt install maven -y"
echo ""
echo "# Verify installations"
echo "java -version"
echo "mvn -version"
echo ""
echo "==============================================="
echo "After installation, you can run:"
echo "cd /mnt/c/Users/frich/Desktop/Micro-Social-Ecommerce-Ecosystems/Exalt-Application-Limited/social-ecommerce-ecosystem/courier-services"
echo "./test-courier-services.sh"
echo "==============================================="